export type Prediction = {
  date: string;
  tournament: string;
  home_team: string;
  away_team: string;
  group: string | null;
  tournament_stage: string;
  is_group_stage: boolean;
  is_knockout_stage: boolean;
  is_extra_time_possible: boolean;
  is_penalty_possible: boolean;
  model_home_expected_goals: number;
  model_away_expected_goals: number;
  context_home_expected_goals: number;
  context_away_expected_goals: number;
  context_home_attack_multiplier: number;
  context_home_defense_multiplier: number;
  context_away_attack_multiplier: number;
  context_away_defense_multiplier: number;
  context_draw_probability_multiplier: number;
  context_applied: boolean;
  context_confidence: string | null;
  context_notes: string | null;
  strategy_home_expected_goals: number;
  strategy_away_expected_goals: number;
  market_adjusted_home_expected_goals: number;
  market_adjusted_away_expected_goals: number;
  home_expected_goals: number;
  away_expected_goals: number;
  goal_inflation: number;
  dynamic_goal_inflation: number;
  stage_adjusted_goal_inflation: number;
  dynamic_goal_inflation_reason: string;
  inflation_warning_flag: boolean;
  inflation_warning_reason: string | null;
  max_total_candidate_goals: number;
  draw_probability_multiplier: number;
  is_last_group_match: boolean;
  home_needs_win: boolean;
  away_needs_win: boolean;
  home_draw_is_enough: boolean;
  away_draw_is_enough: boolean;
  competitive_context_applied: boolean;
  home_already_qualified: boolean;
  away_already_qualified: boolean;
  home_eliminated: boolean;
  away_eliminated: boolean;
  home_goal_difference_pressure: boolean;
  away_goal_difference_pressure: boolean;
  match_pressure_score: number;
  group_scenario_volatility: number;
  home_must_advance: boolean;
  away_must_advance: boolean;
  knockout_match_importance: number;
  extra_time_risk: number;
  penalty_risk: number;
  knockout_draw_boost: number;
  favorite_caution_factor: number;
  underdog_low_block_factor: number;
  late_game_opening_factor: number;
  home_win_probability: number;
  draw_probability: number;
  away_win_probability: number;
  predicted_90min_scoreline: string;
  predicted_advancing_team: string | null;
  advancement_probability_home: number | null;
  advancement_probability_away: number | null;
  extra_time_probability: number;
  penalty_shootout_probability: number;
  market_home_win_probability: number | null;
  market_draw_probability: number | null;
  market_away_win_probability: number | null;
  market_90min_home_probability: number | null;
  market_90min_draw_probability: number | null;
  market_90min_away_probability: number | null;
  market_advance_home_probability: number | null;
  market_advance_away_probability: number | null;
  market_over_2_5_probability: number | null;
  market_under_2_5_probability: number | null;
  market_btts_yes_probability: number | null;
  market_btts_no_probability: number | null;
  market_btts_probability: number | null;
  home_market_edge: number | null;
  draw_market_edge: number | null;
  away_market_edge: number | null;
  market_disagreement_score: number | null;
  market_warning_flag: boolean;
  market_warning_reason: string | null;
  risk_profile: 'conservative' | 'balanced' | 'aggressive' | 'desperation';
  conservative_scoreline: string;
  conservative_expected_points: number;
  balanced_scoreline: string;
  balanced_expected_points: number;
  aggressive_scoreline: string;
  aggressive_expected_points: number;
  desperation_scoreline: string;
  desperation_expected_points: number;
  aggressive_total_goal_cap: number | null;
  desperation_total_goal_cap: number | null;
  risk_adjusted_candidate_scorelines: string;
  recommended_scoreline_by_risk: string;
  estimated_pick_popularity: number;
  differential_multiplier: number;
  upside_multiplier: number;
  strategic_pick_value: number;
  expected_points_drop_vs_balanced: number;
  strategic_override_allowed: boolean;
  strategic_override_reason: string;
  confidence_level: string;
  error_risk: string;
  main_reasons: string;
  alert_flags: string | null;
  recommended_pick_type: string;
  recommended_pick_explanation: string;
  safer_alternative_scoreline: string;
  safer_alternative_reason: string;
  aggressive_alternative_scoreline: string;
  aggressive_alternative_reason: string;
  model_warning_summary: string | null;
  recommended_scoreline: string;
  recommended_expected_points: number;
  draw_alternative_scoreline: string;
  draw_alternative_expected_points: number;
  draw_alternative_is_competitive: boolean;
  same_day_scoreline_count: number;
  scoreline_diversity_penalty: number;
  diversified_recommended_scoreline: string;
  home_elo: number;
  away_elo: number;
  elo_diff: number;
};

export type PredictionAudit = {
  date: string;
  tournament: string;
  home_team: string;
  away_team: string;
  home_score: number;
  away_score: number;
  model_home_expected_goals: number;
  model_away_expected_goals: number;
  home_expected_goals: number;
  away_expected_goals: number;
  home_win_probability: number;
  draw_probability: number;
  away_win_probability: number;
  recommended_home_score: number;
  recommended_away_score: number;
  recommended_scoreline: string;
  recommended_expected_points: number;
  expected_effectiveness: number;
  actual_points: number;
  actual_effectiveness: number;
  actual_category: string;
  result_correct: boolean;
  exact_score: boolean;
};

export type GroupSimulation = {
  team: string;
  group: string;
  first_probability: number;
  second_probability: number;
  third_probability: number;
  fourth_probability: number;
  advance_probability: number;
};

export type TournamentSimulation = {
  team: string;
  group: string;
  round_of_32_probability: number;
  round_of_16_probability: number;
  quarterfinal_probability: number;
  semifinal_probability: number;
  final_probability: number;
  champion_probability: number;
  runner_up_probability: number;
  third_place_probability: number;
  podium_expected_points: number;
};

export type TopScorer = {
  player: string;
  team: string;
  expected_goals: number;
  top_scorer_score: number;
  estimated_team_tournament_goals: number;
};

export type QualificationBacktestStrategy = {
  rank: number;
  goal_inflation: number;
  max_total_candidate_goals: number | null;
  draw_probability_multiplier: number;
  matches: number;
  total_points: number;
  average_points: number;
  exact_scores: number;
  exact_score_rate: number;
  result_accuracy_rate: number;
  winner_and_diff: number;
  draws: number;
  winners: number;
  misses: number;
  miss_rate: number;
  average_pick_goals: number;
  high_total_pick_rate: number;
  selected_strategy: boolean;
  training_window: string;
  validation_window: string;
  training_matches: number;
  training_feature_rows: number;
  validation_matches: number;
  home_mae: number;
  away_mae: number;
};

export type QualificationBacktestPick = {
  date: string;
  home_team: string;
  away_team: string;
  home_score: number;
  away_score: number;
  home_expected_goals: number;
  away_expected_goals: number;
  strategy_home_expected_goals: number;
  strategy_away_expected_goals: number;
  optimized_home_score: number;
  optimized_away_score: number;
  optimized_expected_points: number;
  optimized_points: number;
  optimized_category: string;
  strategy_goal_inflation: number;
  strategy_max_total_candidate_goals: number | null;
  strategy_draw_probability_multiplier: number;
};

export type Metadata = {
  generated_at: string;
  source: string;
  group_simulations: number;
  tournament_simulations: number;
  simulation_seed: number;
};

export type DashboardData = {
  predictions: Prediction[];
  predictionAudit: PredictionAudit[];
  groups: GroupSimulation[];
  tournament: TournamentSimulation[];
  topScorers: TopScorer[];
  qualificationBacktestStrategies: QualificationBacktestStrategy[];
  qualificationBacktestPicks: QualificationBacktestPick[];
  metadata: Metadata;
};
